### ISSUE TITLE
Stopped

### ISSUE THREAD

**Issue by ibrahimhaleemkhan** [davidwarshawsky/Easy-Apply-Automater#1]
Does not work.

**Comment by davidwarshawsky** [comment]
Yes, this is as intended. Here's a link to the new updated one. It's available as a chrome extension. I will no longer be sharing the source code. This is a portfolio project that I have greatly expanded upon in the past 10 months. I will be coming out with new pushes on a regular basis. Please read the description before using. I'm working on changing its logic to work with Single Page Application that LinkedIn is. Right now it might not appear(the image icons to apply to one easy apply job individually) until you go to the next page or refresh on the jobs. I'm actively working on it. Once you go the next page it should show the individual buttons to apply individually perfectly. This is a coming change. Please take a look at the chrome web store and try it out,  I'd love your feedback.

https://chromewebstore.google.com/detail/easy-apply-automater/ejfeogcolgcgfhbfjgbllcijcapaambo

**Comment by timurguseynov** [comment]
Hi @davidwarshawsky, 

Thank you for great work! 

When do you plan to release a new version that supports SPA?

**Comment by davidwarshawsky** [comment]
I am waiting on approval for release of it, I already submitted it to the
chrome store. It should be released soon.

**Comment by timurguseynov** [comment]
@davidwarshawsky Thank you for letting me know :) I'm looking forward to it!

**Comment by davidwarshawsky** [comment]
The new version is live and working now

**Comment by timurguseynov** [comment]
@davidwarshawsky thank you!

**Comment by timurguseynov** [comment]
@davidwarshawsky for some reason it's not working, it's quickly going through jobs without applying, also the button isn't added under .artdeco-entity-lockup__title

**Comment by davidwarshawsky** [comment]
Sorry for the confusion, I was replying to you by email and thought this was direct from the chrome web store. The new code is not public. It's published under the chrome web store. No need to implement it yourself anymore.

https://chromewebstore.google.com/detail/easy-apply-automater/ejfeogcolgcgfhbfjgbllcijcapaambo

**Comment by davidwarshawsky** [comment]
I'm making a new video explaining how the new version 1.1.0 works

**Comment by timurguseynov** [comment]
@davidwarshawsky tried to reinstall and still doesn't work, 

```
  "name": "Easy Apply Automater",
  "version": "1.1.0",
```

**Comment by timurguseynov** [comment]
@davidwarshawsky I tried the version from the chrome store https://chromewebstore.google.com/detail/easy-apply-automater/ejfeogcolgcgfhbfjgbllcijcapaambo. Which is 1.1.0. And it's not working. It quickly goes through all the items and never applies.


![image](https://github.com/user-attachments/assets/3789269a-16a1-414b-9335-dfe589c63714)

![image](https://github.com/user-attachments/assets/7c5418b2-18be-43a2-949a-333adfa8f57c)

**Comment by davidwarshawsky** [comment]
Update out in a day or two.

**Comment by timurguseynov** [comment]
@davidwarshawsky thank you!

**Comment by davidwarshawsky** [comment]
It's fixed, should be approved soon.
